### ISSUE TITLE
Mysql issue

### ISSUE THREAD

**Issue by ben-haim** [Kunstmaan/hands-on-with-multichain#1]
Hi There,
Do you know why im getting this pls ?

 [Doctrine\DBAL\Exception\ConnectionException]
  An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

  [PDOException]
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

  [PDOException]
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by roderik** [comment]
your database settings are incorrect. Did you use the Docker Compose file included in the repo?

**Comment by ben-haim** [comment]
Yeap ... did you try your repo ? something wrong with abe -> mysql ( python ).

Thank you very much for answering me :+1:

**Comment by roderik** [comment]
Indeed, lots of stuff was broken due to new docker images and a jsonrpc client release. Fixed those. But these were not related to the mysql issue. This seems to work perfectly here.

could you provide a:
- docker-compose ps
- docker-compose logs mysql

**Comment by ben-haim** [comment]
Awesome .!!!  \o/

**Comment by ben-haim** [comment]
Sorry disturbing you again .. I got this any idea ? pls ... appreciated your help :-)

PHP Fatal error:  Uncaught TypeError: Argument 3 passed to JsonRPC\Client::__construct() must be an instance of JsonRPC\HttpClient, array given, called in /src/otc/comp/vendor/kunstmaan/libphp-multichain/src/be/kunstmaan/multichain/MultichainClient.php on line 49 and defined in /src/otc/comp/vendor/fguillot/json-rpc/src/JsonRPC/Client.php:66
Stack trace:
#0 /src/otc/comp/vendor/kunstmaan/libphp-multichain/src/be/kunstmaan/multichain/MultichainClient.php(49): JsonRPC\Client->__construct('http://mulichai...', 3, Array)
#1 /src/otc/comp/src/Multichain/Console/Shared/MultichainCommands.php(23): be\kunstmaan\multichain\MultichainClient->__construct('http://mulichai...', 'multichainrpc', 'this-is-insecur...', 3)
#2 /src/otc/comp/src/Multichain/Console/Command/CreateAddressCommand.php(31): Multichain\Console\Command\CreateAddressCommand->connectMultichain()
#3 /src/otc/comp/vendor/symfony/console/Command/Command.php(256): Multichain\Console\Command\CreateAddressCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Objec in /src/otc/comp/vendor/fguillot/json-rpc/src/JsonRPC/Client.php on line 66

**Comment by roderik** [comment]
make sure you do a git pull and a composer update, this error was fixed by my changes yesterday
